package AST;

public interface ASTVisitor {
    void visit(arraycrtNode it);
    void visit(arrayExprNode it);
    void visit(assignExprNode it);
    void visit(atomExprNode it);
    void visit(basiccrtNode it);
    void visit(binaryExprNode it);
    void visit(blockNode it);
    void visit(breakStmtNode it);
    void visit(classconNode it);
    void visit(classcrtNode it);
    void visit(classdefNode it);
    void visit(continueStmtNode it);
    void visit(creatorNode it);
    void visit(emptyStmtNode it);
    void visit(ExprNode it);
    void visit(forStmtNode it);
    void visit(funcalExprNode it);
    void visit(fundefNode it);
    void visit(funparlistNode it);
    void visit(ifStmtNode it);
    void visit(literalNode it);
    void visit(memberExprNode it);
    void visit(newExprNode it);
    void visit(PartNode it);
    void visit(preExprNode it);
    void visit(primaryNode it);
    void visit(ProgramNode it);
    void visit(pureExprStmtNode it);
    void visit(returnStmtNode it);
    void visit(StmtNode it);
    void visit(sufExprNode it);
    void visit(suiteNode it);
    void visit(typeNode it);
    void visit(vardefNode it);
    void visit(vardefStmtNode it);
    void visit(variableNode it);
    void visit(whileStmtNode it);
}
